### ISSUE TITLE
Deleted podcast are visible in Server Settings->Policies

### ISSUE THREAD

**Issue by RadekSip** [dennisreimann/btcpayserver-plugin-podserver#5]
As a new user of BTCPay server, I tried this plugin.
Deleted podcast are visible in Server Settings->Policies and uninstallation of PodServer plugin causes exception on Policies page.

Steps to reproduce:
1. create some podcasts
2. delete them
3. go to Server Settings -> Policies
4. deleted items are still still visible
5. uninstall PodServer plugin
6. go to Server Settings->Policies
7. the page is not loaded, in log is exception

The result is, I have to installed PodServer plugin, because without it, the page cannot be loaded.
I tried the restart, it did not helped.

Error in Server Settings->Policies with uninstalled PodServer
2023-06-03 09:41:01.755 +00:00 [ERR] Connection id "xxx", Request id "xxx": An unhandled exception was thrown by the application.
**System.Collections.Generic.KeyNotFoundException: The given key 'PodServer' was not present in the dictionary.**
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BTCPayServer.Controllers.UIServerController.<>c__DisplayClass39_0.<GetAppSelectList>b__0(ListAppViewModel a) in /source/BTCPayServer/Controllers/UIServerController.cs:line 428
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at BTCPayServer.Controllers.UIServerController.GetAppSelectList() in /source/BTCPayServer/Controllers/UIServerController.cs:line 426
   at **BTCPayServer.Controllers.UIServerController.Policies() in /source/BTCPayServer/Controllers/UIServerController.cs:line 306**

**Comment by RadekSip** [comment]
![deleted-podcasts](https://github.com/dennisreimann/btcpayserver-plugin-podserver/assets/25639785/536b4770-52d7-420b-bb3a-38111c498d08)
These podcasts were deleted/removed. See also possible duplication of name (I tried to created same name and try to delete it again).

**Comment by RadekSip** [comment]
I confirm that the non-existent podcasts were removed after the upgrade.
I also tested creating and deleting a podcast, the podcast appeared and disappeared correctly from Server Settings -> Policies

**Comment by dennisreimann** [comment]
Thanks @RadekSip!
